services:
  devopsproject:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: devopsproject
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge